api/urls.py
from django.urls import path
from .views import LoginAPIView,UserLogout,UserList,Register,ExcelReportView,ComplejoDeportivoListView,ReservasPorUsuario
from .transbank import TransbankCreateView, TransbankCommitView, TransbankReverseOrCancelView
from . import views

app_name = 'api'

urlpatterns = [
    path('log/', LoginAPIView.as_view(), name='login'),
    path('out/', UserLogout.as_view(), name='logout'),
    path('list-user/', UserList().as_view()),
    path('register-user/', Register().as_view()),
    # update_user
    # update_pass
    # Reporte
    path('generate_excel/', ExcelReportView.as_view(), name='generate_excel'),
    #transbank
    path('transbank/transaction/create', TransbankCreateView.as_view()),
    path('transbank/transaction/commit/<str:tokenws>', TransbankCommitView.as_view()),
    path('transbank/transaction/reverse-or-cancel/<str:tokenws>', TransbankReverseOrCancelView.as_view()),

    #funciones para movil
    path('reserva/codigo/', views.ReservaPorCodigoAPIView.as_view(), name='reserva-por-codigo'),


     #funciones para complejos
    path('depo/', ComplejoDeportivoListView.as_view(), name='depo'),



     ##reservas
    path('reservas/<str:username>/', ReservasPorUsuario.as_view(), name='obtener_reservas'),]

cliente/urls.py
from django.urls import path

from . import transbank
from . import views
from .transbank import confirm_transaction

app_name = 'cliente'

urlpatterns = [
    path('list/', views.cliente_list, name='cliente_list'),
    path('create/', views.crear_cliente, name='cliente_create'),
    path('update/<int:pk>/', views.cliente_update, name='cliente_update'),
    path('delete/<int:pk>/', views.cliente_delete, name='cliente_delete'),

    path('reservas/', views.reserva_list, name='reserva_list'),
    path('reservas_user/', views.listar_reservas_usuario, name='listar_reservas_usuario'),
    path('reserva/crear/<int:agenda_id>/', views.crear_reserva, name='crear_reserva'),
    path('confirm-transaction/', confirm_transaction, name='confirm_transaction'),

    path('eliminar/<int:reserva_id>/', views.eliminar_reserva, name='eliminar_reserva'),

    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import *
from . import guard

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('account/', include('accounts.urls')),
    path('servicio/', include('servicio.urls')),
    path('cliente/', include('cliente.urls')),
    path('auth/', include('login.urls')),
    
    ######## LOGIN API REST ########
    path('api/', include('api.urls')),
    ######### PAGES #################
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),
]

handler404 = guard.handler404
handler505 = guard.handler505
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cliente/models.py
from django.db import models
from servicio.models import Agenda
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from servicio.models import Agenda



class Cliente(models.Model):
    SEXO = [
        ('F', 'Femenino'),
        ('M', 'Masculino'),
    ]
    user = models.OneToOneField(
        'accounts.User',
        verbose_name='Usuario',
        on_delete=models.CASCADE
    )
    rut = models.CharField(max_length=10)
    sexo = models.CharField(max_length=10, choices=SEXO)

    def __str__(self):
        return f'{self.user.username}'

class Reserva(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)
    dia = models.DateField()
    ESTADO_CHOICES = [
        ('disponible', 'Disponible'),
        ('pendiente', 'Pendiente'),
        ('finalizada', 'Finalizada'),
    ]
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='disponible')

    class Meta:
        unique_together = ('agenda', 'cliente', 'dia')

    def __str__(self):
        formatted_date = self.dia.strftime('%d-%m-%Y')
        return f"Reserva de {self.cliente} para el {formatted_date}, {self.agenda.cancha} {self.agenda.horario}"


#CREA UNA BOLETA AUTOMATICAMENTE CUANDO SE CREA UNA RESERVA
@receiver(post_save, sender=Reserva)
def crear_boleta(sender, instance, created, **kwargs):
    if created or (not instance._state.adding and instance.estado == 'pendiente'):
        # Obtén el tipo de cancha asociado a la reserva
        tipo_cancha = instance.agenda.cancha.tipo
        # Calcula la mitad del precio del tipo de cancha
        mitad_precio = tipo_cancha.precio / 2
        # Crea una instancia de Boleta con el valor calculado
        Boleta.objects.create(cliente=instance.cliente, reserva=instance, total=mitad_precio)


class Ticket(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    codigo = models.CharField(max_length=10)
    fecha_envio = models.DateTimeField(auto_now_add=True)
    reserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)

class Boleta(models.Model):
    fecha_emision = models.DateTimeField(default=timezone.now)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    reserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2) 

    def __str__(self):
        return f'Boleta para {self.cliente} emitida el {self.fecha_emision}'

cliente/forms.py
from django import forms
from .models import Reserva
from django.utils import timezone
import datetime
from .models import Cliente
import calendar
from datetime import timedelta
from django.core.exceptions import ValidationError


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ['rut','sexo']

    def clean_rut(self):
        rut = self.cleaned_data['rut']
        rut = rut.upper()  # Convertir el Rut a mayúsculas
        rut = rut.replace(".", "")  # Eliminar los puntos del Rut
        rut = rut.replace("-", "")  # Eliminar el guión del Rut

        # Extraer el dígito verificador y el número base del Rut
        dv = rut[-1]
        rut_base = rut[:-1]

        # Validar que el número base del Rut sea un entero
        try:
            int(rut_base)
        except ValueError:
            raise forms.ValidationError('El Rut ingresado no es válido.')

        # Calcular el dígito verificador esperado
        suma = 0
        multiplicador = 2
        for digito in reversed(rut_base):
            suma += int(digito) * multiplicador
            multiplicador += 1
            if multiplicador == 8:
                multiplicador = 2

        resto = suma % 11
        dv_esperado = str(11 - resto) if resto > 1 else '0'

        # Comparar el dígito verificador calculado con el ingresado
        if dv != dv_esperado:
            raise forms.ValidationError('El Rut ingresado no es válido.')

        return rut



class ReservaForm(forms.ModelForm):
    dia = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))

    class Meta:
        model = Reserva
        fields = ['dia']
        
    def clean_dia(self):
        dia = self.cleaned_data.get('dia')
        fecha_actual = timezone.now().date()
        fecha_limite = fecha_actual + timedelta(days=1)
        fecha_maxima = fecha_actual + timedelta(weeks=2) 

        if dia < fecha_limite:
            raise forms.ValidationError("Debes realizar la reserva con al menos un día de anticipación.")
        if dia < fecha_actual:
            raise forms.ValidationError("No puedes reservar una fecha pasada.")
        if dia > fecha_maxima:
            raise forms.ValidationError("No puedes reservar con más de dos semanas de anticipación.")

        if dia.weekday() == calendar.SUNDAY:
            raise forms.ValidationError("Los domingos no se pueden reservar.")
    
        agenda = self.cleaned_data.get('agenda')
        if Reserva.objects.filter(agenda=agenda, dia=dia).exists():
            raise forms.ValidationError("La fecha ya está reservada.")

        return dia

cliente/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .models import Reserva, Agenda, Cliente,Ticket
from django.contrib import messages
from .forms import ReservaForm, ClienteForm
from django.contrib.auth.decorators import login_required
import json
from django.utils import timezone
from datetime import datetime
import requests
from django.conf import settings
from django.urls import reverse
import random
import string
from .transbank import crear_transaccion

from accounts.decorators import has_permission
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


#cliente
from django.shortcuts import render
from .models import Cliente
from accounts.models import Rol
from django.contrib.auth.decorators import login_required

@login_required
def cliente_list(request):
    # Obtén el rol de "cliente"
    cliente_role, created = Rol.objects.get_or_create(nombre='cliente')
    # Filtra los usuarios que tienen el rol de "cliente"
    clientes = Cliente.objects.filter(user__roles=cliente_role)

    context = {'clientes': clientes}
    return render(request, 'cliente/listar.html', context)


#ESTA FUNCION ES PARA RECORDAR RELLENAR TODOS SUS DATOS
def crear_cliente(request):
    cliente_existente = Cliente.objects.filter(user=request.user).first()  # Verificar si existe un cliente para el usuario actual

    if cliente_existente:  # Si el cliente existe, rellenar los datos en el formulario
        form = ClienteForm(instance=cliente_existente)
    else:
        form = ClienteForm()

    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente_existente)  # Pasar la instancia existente al formulario en caso de edición

        try:
            if form.is_valid():
                cliente = form.save(commit=False)
                cliente.user = request.user
                cliente.save()
                return redirect('servicio:agenda-reserva')
        except Exception as e:
            error_message = str(e)
            form.add_error(None, error_message)

    return render(request, 'cliente/agregar.html', {'form': form})

def cliente_update(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('cliente:cliente_list')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'cliente/modificar.html', {'form': form})

def cliente_delete(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        cliente.delete()
        messages.success(request, 'Cliente deleted successfully.')
        return redirect(to='cliente_list')
    else:
        messages.warning(request, 'Invalid request.')
        return redirect(to='cliente_list')

#reservas ( las reservas no se eliminan , solo de lista,crean,modifican)
def reserva_list(request):
    reservas = Reserva.objects.all()
    today = timezone.now().date()
    return render(request, 'reserva/listar.html', {'reservas': reservas, 'today': today})

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Reserva

def listar_reservas_usuario(request):
    try:
        cliente = request.user.cliente
    except Cliente.DoesNotExist:
        messages.warning(request, 'Necesitas crear un Cliente para acceder a esta página')
        return redirect(reverse('cliente:cliente_create'))

    # Filtrar reservas por estado "pendiente" o "finalizada"
    reservas_pendientes_finalizadas = Reserva.objects.filter(cliente=cliente, estado__in=['pendiente', 'finalizada'])

    return render(request, 'reserva/reservas_usuario.html', {'reservas': reservas_pendientes_finalizadas})




def eliminar_reserva(request, reserva_id):
    reserva = get_object_or_404(Reserva, id=reserva_id)
    # Verifica si el usuario tiene permisos para eliminar la reserva
    if request.user.cliente == reserva.cliente:
        reserva.delete()
        messages.success(request, 'Reserva cancelada correctamente.')
    else:
        messages.error(request, 'No tienes permisos para cancelar esta reserva.')

    return redirect('cliente:listar_reservas_usuario')



def crear_reserva(request, agenda_id):
    agenda = get_object_or_404(Agenda, id=agenda_id)
    form = ReservaForm(initial={'agenda': agenda})

    try:
        cliente = request.user.cliente
    except Cliente.DoesNotExist:
        messages.warning(request, 'Necesitas los DATOS COMPLEMENTARIOS para realizar una reserva')
        return redirect(to='cliente:cliente_create')

    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            reserva = form.save(commit=False)
            reserva.agenda = agenda
            reserva.cliente = cliente
            if Reserva.objects.filter(agenda=agenda, dia=reserva.dia).exists():
                messages.error(request, 'La fecha ya está reservada.')
            else:
                amount = agenda.cancha.tipo.precio / 2
                transaction_data = crear_transaccion(request, agenda, amount)
                if transaction_data:
                    #guardar reserva en la sesion
                    reserva_session = request.session['reserva_actual'] = reserva
                    print(f'reserva actual: {reserva_session}')
                    return render(request, 'reserva/crear.html', {'transaction_data': transaction_data})
                else:
                    return render(request, 'pages/home.html')

    dias_reservados = Reserva.objects.filter(agenda__cancha=agenda.cancha, agenda__horario=agenda.horario).values_list('dia', flat=True)
    dias_reservados_str = ', '.join([dia.strftime('%d/%m/%Y') for dia in dias_reservados])
    dias_reservados_json = json.dumps(dias_reservados_str)

    contexto = {
        'form': form,
        'agenda': agenda,
        'dias_reservados_json': dias_reservados_json,
    }
    return render(request, 'reserva/crear.html', contexto)
#Modificar reserva

#Ticket
#Boleta

cliente/templates/cliente/agregar.html
{% extends "accounts/index.html" %}

{% block accounts_container %}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Editar Cliente</h1>
        </div>
        <div class="card-body">
            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                
                <div class="form-group">
                    <label class="col-md-3 control-label">RUT</label>
                    <div class="col-md-9">
                        {{ form.rut }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Sexo</label>
                    <div class="col-md-9">
                        <select class="form-control" name="{{ form.sexo.name }}">
                            {% for value, label in form.sexo.field.choices %}
                                <option value="{{ value }}" {% if form.sexo.value == value %}selected{% endif %}>
                                    {{ label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </div>
                {% for field in form %}
                    {% if field.errors %}
                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3">
                                {% for error in field.errors %}
                                    <div class="error">{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

cliente/templates/cliente/listar.html
{% extends "layout.html" %}

{% load static %}
{% load humanize %}

{% block title %}
Clientes | {{ block.super }}
{% endblock %}

{% block container %}
<div class="container">
  <br>
  <div class="card">
    <div class="card-header">
      Lista de Clientes
    </div>
    <div class="card-body">
      <div class="table-responsive text-center">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre de Usuario </th>
              <th>RUT</th>
              <th>Sexo</th>
              <th>Códigos de Ticket</th>
              <th>Reservas</th>
            </tr>
          </thead>
          <tbody>
            {% for cliente in clientes %}
            <tr>
              <td>{{ cliente.id }}</td>
              <td>{{ cliente.user.username }}</td>
              <td>{{ cliente.rut }}</td>
              <td>{{ cliente.get_sexo_display }}</td>
              <td>
                {% for ticket in cliente.ticket_set.all %}
                <a class="btn ticket-modal-button" data-target="#ticketModal{{ ticket.codigo }}" data-toggle="modal"
                  style="margin-top: -10px;">{{ ticket.codigo }}&#10230;</a><br>
                {% endfor %}
              </td>
              <td>
                {% for reserva in cliente.reserva_set.all %}
                {{ reserva.get_estado_display }}<br>
                {% endfor %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {% for cliente in clientes %}
  {% for ticket in cliente.ticket_set.all %}
  <div class="modal fade" id="ticketModal{{ ticket.codigo }}" tabindex="-1" role="dialog"
    aria-labelledby="ticketModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="ticketModalLabel">Detalles de Reserva</h4>
          <div data-dismiss="modal" aria-label="Close" style="cursor: pointer;">
            <span id="close-modal" aria-hidden="true" style="font-size: 1.5rem;">&times;</span>
          </div>
        </div>
        <div class="modal-body text-start">
          <p>Cliente: {{ cliente.user.username }}</p>
          <p>Rut: {{ cliente.rut }}</p>
          <p>Fecha de Reserva: {{ ticket.reserva.dia }}</p>
          <p>Horario: {{ ticket.reserva.agenda.horario }}</p>
          <p>N° de Cancha: {{ ticket.reserva.agenda.cancha }}</p>
          <p>Tipo: {{ ticket.reserva.agenda.cancha.tipo }}</p>
          <hr>
          <h4>Boleta(s)</h4>
          <hr>
          {% for boleta in ticket.reserva.boleta_set.all %}
          <p>Fecha de Emisión: {{ boleta.fecha_emision }}</p>
          <p>Total: {{ boleta.total }}</p>
          <hr>
          {% empty %}
          <p>No se encontraron boletas</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endfor %}
</div>

{% endblock %}

cliente/templates/cliente/modificar.html
{% extends "accounts/index.html" %}

{% block accounts_container %}

<div class="container">
  <h1>update pass</h1>
  <form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    {{form}}
    <div class="form-group">
      <div class="col-md-9 col-md-offset-3">
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </div>
  </form>

</div>


{% endblock %}