accounts/urls.py
from django.urls import path
from . import views
from . import roles_permisos
from .roles_permisos import RolDetailView,RolListView
from .views import edit_user
from .views import EliminarUsuarioView




app_name = 'account'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('registro-user/', views.register, name='register'),

    path('update-user/', views.update_user, name='update_user'),
    path('update-pass/', views.update_password, name='update_password'),
 
    path('user-list/', views.user_list, name='user_list'),
    path('user-admin-list/', views.user_admin_list, name='user_admin_list'),
    path('user-delete/<int:pk>/', views.user_delete, name='user_delete'),
    
    #ROLES Y PERMISOS
    path('roles/', RolListView.as_view(), name='rol-list'),
    path('rol/<int:pk>/', RolDetailView.as_view(), name='rol-det'),
    path('eliminar_usuario/<int:user_id>/', EliminarUsuarioView.as_view(), name='eliminar_usuario'),
    path('usuario/<int:user_id>/edit/', edit_user, name='edit_user'),

]

api/urls.py
from django.urls import path
from .views import LoginAPIView,UserLogout,UserList,Register,ExcelReportView,ComplejoDeportivoListView,ReservasPorUsuario
from .transbank import TransbankCreateView, TransbankCommitView, TransbankReverseOrCancelView
from . import views

app_name = 'api'

urlpatterns = [
    path('log/', LoginAPIView.as_view(), name='login'),
    path('out/', UserLogout.as_view(), name='logout'),
    path('list-user/', UserList().as_view()),
    path('register-user/', Register().as_view()),
    # update_user
    # update_pass
    # Reporte
    path('generate_excel/', ExcelReportView.as_view(), name='generate_excel'),
    #transbank
    path('transbank/transaction/create', TransbankCreateView.as_view()),
    path('transbank/transaction/commit/<str:tokenws>', TransbankCommitView.as_view()),
    path('transbank/transaction/reverse-or-cancel/<str:tokenws>', TransbankReverseOrCancelView.as_view()),

    #funciones para movil
    path('reserva/codigo/', views.ReservaPorCodigoAPIView.as_view(), name='reserva-por-codigo'),


     #funciones para complejos
    path('depo/', ComplejoDeportivoListView.as_view(), name='depo'),



     ##reservas
    path('reservas/<str:username>/', ReservasPorUsuario.as_view(), name='obtener_reservas'),]

cliente/urls.py
from django.urls import path

from . import transbank
from . import views
from .transbank import confirm_transaction

app_name = 'cliente'

urlpatterns = [
    path('list/', views.cliente_list, name='cliente_list'),
    path('create/', views.crear_cliente, name='cliente_create'),
    path('update/<int:pk>/', views.cliente_update, name='cliente_update'),
    path('delete/<int:pk>/', views.cliente_delete, name='cliente_delete'),

    path('reservas/', views.reserva_list, name='reserva_list'),
    path('reservas_user/', views.listar_reservas_usuario, name='listar_reservas_usuario'),
    path('reserva/crear/<int:agenda_id>/', views.crear_reserva, name='crear_reserva'),
    path('confirm-transaction/', confirm_transaction, name='confirm_transaction'),

    path('eliminar/<int:reserva_id>/', views.eliminar_reserva, name='eliminar_reserva'),

    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import *
from . import guard

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('account/', include('accounts.urls')),
    path('servicio/', include('servicio.urls')),
    path('cliente/', include('cliente.urls')),
    path('auth/', include('login.urls')),
    
    ######## LOGIN API REST ########
    path('api/', include('api.urls')),
    ######### PAGES #################
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),
]

handler404 = guard.handler404
handler505 = guard.handler505
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import UserManager
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin)
from django.db.models.signals import pre_save,post_migrate
from django.dispatch import receiver
from django.db import models, transaction 


class Region(models.Model):

    REGIONES_CHOICES = [
    ('Metropolitana de Santiago', 'Metropolitana de Santiago'),
    ('Tarapacá', 'Tarapacá'),
    ('Antofagasta', 'Antofagasta'),
    ('Atacama', 'Atacama'),
    ('Coquimbo', 'Coquimbo'),
    ('Valparaíso', 'Valparaíso'),
    ('Libertador General Bernardo O\'Higgins', 'Libertador General Bernardo O\'Higgins'),
    ('Maule', 'Maule'),
    ('Ñuble', 'Ñuble'),
    ('Biobío', 'Biobío'),
    ('La Araucanía', 'La Araucanía'),
    ('Los Ríos', 'Los Ríos'),
    ('Los Lagos', 'Los Lagos'),
    ('Aysén del General Carlos Ibáñez del Campo', 'Aysén del General Carlos Ibáñez del Campo'),
    ('Magallanes y de la Antártica Chilena', 'Magallanes y de la Antártica Chilena'),
    ]
    nombre = models.CharField(max_length=50, choices=REGIONES_CHOICES)
    def __str__(self):
        return self.nombre


@receiver(post_migrate)
def create_regions(sender, **kwargs):
    if sender.name == 'accounts':  
        existing_regions = set(Region.objects.values_list('nombre', flat=True))
        for region_choice in Region.REGIONES_CHOICES:
            region_name = region_choice[0]
            if region_name not in existing_regions:
                Region.objects.create(nombre=region_name)
                existing_regions.add(region_name)


class ComplejoDeportivo(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, default='Metropolitana de Santiago')
    url = models.URLField()
    imagen = models.ImageField(upload_to='static/complejos_deportivos/')
    
    def __str__(self):
        return self.nombre


class Permiso(models.Model):
    CLASES_CHOICES = [
        ('Permiso', 'Permiso'),
        ('Rol', 'Rol'),
        ('User', 'User'),
        ('Cliente', 'Cliente'),
        ('Reserva', 'Reserva'),
        ('Ticket', 'Ticket'),
        ('Boleta', 'Boleta'),
        ('TipoCancha', 'TipoCancha'),
        ('Cancha', 'Cancha'),
        ('Horario', 'Horario'),
        ('Agenda', 'Agenda'),
    ]
    clase = models.CharField(max_length=15, choices=CLASES_CHOICES)
    nombre = models.CharField(max_length=50)

    class Meta:
        unique_together = ('clase', 'nombre')  

    def __str__(self):
        return self.nombre

#ESTE TIPO DE FUNCIONES ES PARA CUANDO SE HAGA EL MIGRATE RELLENAR AUTOMATICO CON PERMISOS POR DEFECTO
@receiver(post_migrate)
def create_default_permissions(sender, **kwargs):
    if sender.name == 'accounts':
        with transaction.atomic():
            for choice_value, choice_display in Permiso.CLASES_CHOICES:
                for perm_action in ['crear', 'leer', 'actualizar', 'eliminar']:
                    perm_name = f'{perm_action} {choice_display.lower()}'
                    permiso, _ = Permiso.objects.get_or_create(
                        clase=choice_value,
                        nombre=perm_name
                    )


class Rol(models.Model):
    ROL_CHOICES = [
        ('admin', 'Administrador'),
        ('trabajador', 'Trabajador'),
        ('cliente', 'Cliente'),
    ]

    nombre = models.CharField(max_length=15, unique=True, choices=ROL_CHOICES)
    permisos = models.ManyToManyField(Permiso)

    def __str__(self):
        return self.get_nombre_display()

    class Meta:
        verbose_name_plural = 'roles'


class CustomUserManager(UserManager):
    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        admin_role, created = Rol.objects.get_or_create(nombre='admin')
        extra_fields['roles'] = admin_role

        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True, unique=True)
    username = models.CharField(
        'Usuario', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'ingrese un nombre de usuario valido '
                'Este valor debe contener solo letras, números '
                'excepto: @/./+/-/_.',
                'invalid'
            )
        ],
        help_text='Un nombre corto que sera usado'+
                  ' para identificarlo de forma unica en la plataforma.'
    )
    name = models.CharField('Nombre', max_length=20)
    apellidos = models.CharField('Apellidos', max_length=30)
    email = models.EmailField('Email', unique=True)
    is_staff = models.BooleanField('Admin', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)
    roles = models.ForeignKey(Rol, on_delete=models.CASCADE, blank=True, null=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(' ')[0]


#ESTA FUNCION HACE QUE SI EL USUARIO CAMBIA SU ROL A ADMINISTRADOR SEA LO MISMO QUE UN SUPER USUARIO
@receiver(pre_save, sender=User)
def update_is_staff(sender, instance, **kwargs):
    if instance.roles and instance.roles.nombre == 'admin':
        instance.is_staff = True
    else:
        if not instance.roles:
            cliente_role, created = Rol.objects.get_or_create(nombre='cliente')
            instance.roles = cliente_role
        instance.is_staff = False

accounts/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from django.core.exceptions import ValidationError

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'name', 'apellidos', 'email', 'is_staff', 'is_active', 'roles']


class UserAdminCreationForm(UserCreationForm):
    
    username = forms.CharField(max_length=20)
    name = forms.CharField(max_length=20)
    apellidos = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=40)
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'name','apellidos', 'email', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 4:
            raise ValidationError('El nombre de usuario debe tener al menos 4 caracteres.')
        if not re.match(r'^[a-zA-Z0-9]+$', username):
            raise ValidationError('El nombre de usuario solo puede contener letras y números.')
        if User.objects.filter(username=username).exists():
            raise ValidationError('Este nombre de usuario ya está en uso.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('Este correo electrónico ya está en uso.')

        if not re.match(r'^[\w\.-]+@(gmail\.com|yahoo\.com|outlook\.com)$', email):
            raise ValidationError('El correo electrónico debe ser de tipo @gmail.com, @yahoo.com, @outlook.com')

        return email


    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise ValidationError('La contraseña debe tener al menos 8 caracteres.')
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Las contraseñas no coinciden.')
        return password2



#FORMULARIOS PARA ROLES Y PERMISOS SI ES QUE ES NECESARIO 

accounts/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, CreateView, UpdateView, FormView, DeleteView
from django.utils.decorators import method_decorator
from .decorators import has_permission
from .models import User, Rol
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserAdminCreationForm

class IndexView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/index.html'
    login_url = reverse_lazy('Login:login')
        
    def get_object(self):
        return self.request.user

from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.shortcuts import get_object_or_404, redirect
from .models import User


from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserChangeForm
from django.contrib import messages

# accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserEditForm
from .models import User

# En tu aplicación/views.py

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .forms import UserEditForm
from .models import User

def edit_user(request, user_id):
    user_to_edit = get_object_or_404(User, id=user_id)
    
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user_to_edit)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario actualizado exitosamente.')
            return redirect('account:user_list')
    else:
        form = UserEditForm(instance=user_to_edit)

    return render(request, 'accounts/edit_user.html', {'form': form, 'user_to_edit': user_to_edit})


def user_list(request):
    users = User.objects.all()
    return render(request, 'accounts/user_list.html', {'users': users})




from django.utils.decorators import method_decorator
from django.views import View
from .decorators import has_permission  

@method_decorator(has_permission(['eliminar user']), name='dispatch')
class EliminarUsuarioView(View):
    def post(self, request, user_id):
        user = get_object_or_404(User, id=user_id)
        user.delete()
        return redirect('account:user_list')
    
    def get(self, request, user_id):
        return redirect('account:user_list')



@method_decorator(has_permission(['leer user']), name='dispatch')
class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'accounts/user_list.html'
    context_object_name = 'users'

@method_decorator(has_permission(['leer user']), name='dispatch')
class UserAdminListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'admin/user_admin.html'
    context_object_name = 'users'

    def get_queryset(self):
        roles_to_filter = ['trabajador']
        return User.objects.filter(roles__nombre__in=roles_to_filter)

@method_decorator(has_permission(['eliminar user']), name='dispatch')
class UserDeleteView(DeleteView):
    model = User
    template_name = 'accounts/user_confirm_delete.html'
    success_url = reverse_lazy('account:user_list')
    context_object_name = 'user'


class RegisterView(CreateView):
    model = User
    form_class = UserAdminCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('account:index')

    def form_valid(self, form):
        cliente_role, created = Rol.objects.get_or_create(nombre='cliente')
        user = form.save(commit=False)
        user.roles = cliente_role
        user.save()

        return super().form_valid(form)

class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    login_url = reverse_lazy('Login:login')
    template_name = 'accounts/update_user.html'
    fields = ['name', 'apellidos', 'email']
    success_url = reverse_lazy('account:index')

    def get_object(self):
        return self.request.user

class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'accounts/update_password.html'
    login_url = reverse_lazy('Login:login')
    success_url = reverse_lazy('account:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_password_validation'] = False
        return context


index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()
user_list = UserListView.as_view()
user_admin_list = UserAdminListView.as_view()
user_delete = UserDeleteView.as_view()

accounts/templates/accounts/edit_user.html
{% extends 'accounts/index.html' %}
{% load custom_filters %}

{% block title %}
  Editar Usuario | {{ block.super }}
{% endblock %}

{% block accounts_container %}
  <style>
    /* Estilos específicos para esta página */

    .card {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      background-color: #fff;
      border-radius: 8px;
    }

    .form-group {
      margin-bottom: 20px;
    }

    .form-label {
      font-weight: bold;
      margin-bottom: 5px;
      display: block;
    }

    .btn-primary {
      background-color: #007bff;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 4px;
      cursor: pointer;
    }

    .btn-secondary {
      background-color: #6c757d;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 4px;
      cursor: pointer;
    }

    /* Añade más estilos generales aquí si es necesario */

  </style>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    var isStaffCheckbox = document.getElementById('{{ form.is_staff.id_for_label }}');
    var rolesField = document.getElementById('{{ form.roles.id_for_label }}');

    // Función para manejar el cambio en el checkbox is_staff
    function handleIsStaffChange() {
      rolesField.disabled = !isStaffCheckbox.checked;  // Deshabilitar el campo de roles si is_staff no está marcado

      // Configurar automáticamente el rol de administrador si is_staff está marcado
      if (isStaffCheckbox.checked) {
        rolesField.value = '1';  // Ajusta el valor correspondiente para el rol de administrador
      } else {
        rolesField.value = '';  // Reiniciar el valor del campo de roles si is_staff no está marcado
      }
    }

    // Agregar el evento de cambio al checkbox is_staff
    isStaffCheckbox.addEventListener('change', handleIsStaffChange);

    // Llamar a la función handleIsStaffChange al cargar la página para establecer el estado inicial
    handleIsStaffChange();
  });
</script>


<div class="container">
  <div class="card">
    <h2 class="text-center">Editar Usuario</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label class="form-label" for="{{ form.username.id_for_label }}">Nombre de Usuario:</label>
        {{ form.username }}
      </div>
      <div class="form-group">
        <label class="form-label" for="{{ form.name.id_for_label }}">Nombre:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label class="form-label" for="{{ form.apellidos.id_for_label }}">Apellidos:</label>
        {{ form.apellidos }}
      </div>
      <div class="form-group">
        <label class="form-label" for="{{ form.email.id_for_label }}">Email:</label>
        {{ form.email }}
      </div>
      <div class="form-group">
        <label class="form-label" for="{{ form.is_staff.id_for_label }}">¿Es administrador?</label>
        {{ form.is_staff }}
      </div>
      <div class="form-group">
        <label class="form-label" for="{{ form.is_active.id_for_label }}">¿Está activo?</label>
        {{ form.is_active }}
      </div>
      <div class="form-group">
        <label class="form-label" for="{{ form.roles.id_for_label }}">Rol:</label>
        {{ form.roles }}
      </div>

      <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        <a href="{% url 'account:user_list' %}" class="btn btn-secondary">Volver al listado de usuarios</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends "layout.html" %}
{% load custom_filters %}

{% block title %}
index | {{ block.super }}
{% endblock %}

{% block container %}

<body class="body">
    <div class="container">
        <br>
        <div class="row">
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <div class="list-group">
                    <a class="list-group-item active">Mi Cuenta</a>
                    {% if user.roles.nombre == 'admin' or user.roles.nombre == 'trabajador' or user.roles.nombre == 'cliente'%}
                    <a href="{% url 'account:update_user'%}" class="list-group-item">modificar usuario</a>
                    <a href="{% url 'account:update_password'%}" class="list-group-item">modificar contraseña</a>               
                    {% endif %}
                    {% if user.roles.nombre == 'cliente'%}
                    <a href="{% url 'cliente:cliente_create' %}" class="list-group-item"> datos complementarios </a>                 
                    {% endif %}
                </div>
                <br>
                <div class="list-group">
                    {% if user.roles.nombre == 'cliente'%}
                    <a href="{% url 'cliente:listar_reservas_usuario' %}" class="list-group-item">Mis reservas</a>
                    {% endif %}
                    {% if user.roles.nombre == 'admin'%}
                    <a class="list-group-item active">Anexos</a>
                    <a href="{% url 'account:user_list' %}" class="list-group-item">Usuarios</a>
                    <a href="{% url 'account:user_admin_list' %}" class="list-group-item">Trabajadores</a>
                    <a href="{% url 'api:generate_excel' %}" class="list-group-item">Reporte</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <!-- ################## listas servicio , reservas , agendas  ################## -->
                {% block accounts_container %}<h2>Bienvenido {{ user.name }} </h2>{% endblock %}

            </div>
        </div>
</body>

{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% block accounts_container %}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Cambio de contraseña</h1>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'account:update_password' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            {{ form.old_password.label_tag }}
                            <input type="password" name="{{ form.old_password.name }}" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            {{ form.new_password1.label_tag }}
                            <input type="password" name="{{ form.new_password1.name }}" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            {{ form.new_password2.label_tag }}
                            <input type="password" name="{{ form.new_password2.name }}" class="form-control">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Cambiar contraseña</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/update_user.html
{% extends 'accounts/index.html' %}

{% block accounts_container %}

<style>
  .form-group {
    margin-bottom: 10px;
  }
</style>

<div class="container">
  <br>
  <div class="card">
    <div class="card-header">
      Usuario
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.name.label_tag }}
          {{ form.name }}
        </div>
        <div class="form-group">
          {{ form.apellidos.label_tag }}
          {{ form.apellidos }}
        </div>
        <div class="form-group">
          {{ form.email.label_tag }}
          {{ form.email }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/user_list.html
{% extends "accounts/index.html" %}
{% load custom_filters %}

{% block title %}
  Lista de Usuarios | {{ block.super }}
{% endblock %}

{% block accounts_container %}
  <style>
    /* Estilos específicos para esta página */

    .card {
      margin-top: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card-header {
      background-color: #007bff;
      color: #fff;
      padding: 15px;
      border-radius: 4px 4px 0 0;
    }

    .card-title {
      margin: 0;
      font-size: 24px;
    }

    .card-body {
      padding: 20px;
    }

    .table {
      width: 100%;
      margin-bottom: 0;
      background-color: #fff;
    }

    .table th, .table td {
      padding: 15px;
      text-align: center;
    }

    .table thead {
      background-color: #f8f9fa;
    }

    .table tbody tr:nth-child(even) {
      background-color: #f8f9fa;
    }

    .table tbody tr:hover {
      background-color: #e9ecef;
    }

    .btn-container {
      display: flex;
      align-items: center;
    }

    .btn-editar,
    .btn-eliminar {
      padding: 8px 12px;
      margin-right: 5px;
      border-radius: 4px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .btn-editar {
      color: #fff;
      background-color: #007bff;
      border: 1px solid #007bff;
    }

    .btn-editar:hover {
      background-color: #0056b3;
    }

    .btn-eliminar {
      color: #dc3545;
      background-color: #fff;
      border: 1px solid #dc3545;
    }

    .btn-eliminar:hover {
      background-color: #f8d7da;
    }

  </style>

  <div class="container">
    <div class="card">
      <div class="card-header">
        <h1 class="card-title">Usuarios</h1>
      </div>
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th>Usuario</th>
              <th>Nombre</th>
              <th>Email</th>
              <th>Rol</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
              <tr {% if user.roles.nombre == "cliente" %}style="background-color: lightgreen;"{% endif %}>
                <td>{{ user.username }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles }}</td>
                <td class="btn-container">
                  <div>
                    <a href="{% url 'account:edit_user' user.id %}" class="btn-editar">Editar</a>
                  </div>
                  <div>
                    <form method="post" action="{% url 'account:eliminar_usuario' user.id %}" style="display: inline-block;">
                      {% csrf_token %}
                      <button type="submit" class="btn-eliminar" onclick="return confirm('¿Estás seguro de eliminar este usuario?')">Eliminar</button>
                    </form>
                  </div>
                </td>              
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}