api/urls.py
from django.urls import path
from .views import LoginAPIView,UserLogout,UserList,Register,ExcelReportView,ComplejoDeportivoListView,ReservasPorUsuario
from .transbank import TransbankCreateView, TransbankCommitView, TransbankReverseOrCancelView
from . import views

app_name = 'api'

urlpatterns = [
    path('log/', LoginAPIView.as_view(), name='login'),
    path('out/', UserLogout.as_view(), name='logout'),
    path('list-user/', UserList().as_view()),
    path('register-user/', Register().as_view()),
    # update_user
    # update_pass
    # Reporte
    path('generate_excel/', ExcelReportView.as_view(), name='generate_excel'),
    #transbank
    path('transbank/transaction/create', TransbankCreateView.as_view()),
    path('transbank/transaction/commit/<str:tokenws>', TransbankCommitView.as_view()),
    path('transbank/transaction/reverse-or-cancel/<str:tokenws>', TransbankReverseOrCancelView.as_view()),

    #funciones para movil
    path('reserva/codigo/', views.ReservaPorCodigoAPIView.as_view(), name='reserva-por-codigo'),


     #funciones para complejos
    path('depo/', ComplejoDeportivoListView.as_view(), name='depo'),



     ##reservas
    path('reservas/<str:username>/', ReservasPorUsuario.as_view(), name='obtener_reservas'),]

cliente/urls.py
from django.urls import path

from . import transbank
from . import views
from .transbank import confirm_transaction

app_name = 'cliente'

urlpatterns = [
    path('list/', views.cliente_list, name='cliente_list'),
    path('create/', views.crear_cliente, name='cliente_create'),
    path('update/<int:pk>/', views.cliente_update, name='cliente_update'),
    path('delete/<int:pk>/', views.cliente_delete, name='cliente_delete'),

    path('reservas/', views.reserva_list, name='reserva_list'),
    path('reservas_user/', views.listar_reservas_usuario, name='listar_reservas_usuario'),
    path('reserva/crear/<int:agenda_id>/', views.crear_reserva, name='crear_reserva'),
    path('confirm-transaction/', confirm_transaction, name='confirm_transaction'),

    path('eliminar/<int:reserva_id>/', views.eliminar_reserva, name='eliminar_reserva'),

    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import *
from . import guard

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('account/', include('accounts.urls')),
    path('servicio/', include('servicio.urls')),
    path('cliente/', include('cliente.urls')),
    path('auth/', include('login.urls')),
    
    ######## LOGIN API REST ########
    path('api/', include('api.urls')),
    ######### PAGES #################
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),
]

handler404 = guard.handler404
handler505 = guard.handler505
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

servicio/urls.py
from django.urls import path
from .views import (
    CanchaListView,
    CanchaCreateView,
    CanchaUpdateView,
    CanchaDeleteView,
    TipoCanchaListView,
    TipoCanchaCreateView,
    TipoCanchaUpdateView,
    TipoCanchaDeleteView,
    AgendaListView,
    AgendaCreateView,
    AgendaUpdateView,
    AgendaDeleteView,
    PreReserva,
)

app_name = 'servicio'

urlpatterns = [
    # Cancha URLs
    path('listar/', CanchaListView.as_view(), name='cancha-listar'),
    path('agregar/', CanchaCreateView.as_view(), name='cancha-crear'),
    path('actualizar/<int:pk>/', CanchaUpdateView.as_view(), name='cancha-actualizar'),
    path('eliminar/<int:pk>/', CanchaDeleteView.as_view(), name='cancha-eliminar'),

    # TipoCancha URLs
    path('tipo/listar/', TipoCanchaListView.as_view(), name='tipo-listar'),
    path('tipo/agregar/', TipoCanchaCreateView.as_view(), name='tipo-agregar'),
    path('tipo/actualizar/<int:pk>/', TipoCanchaUpdateView.as_view(), name='tipo-actualizar'),
    path('tipo/eliminar/<int:pk>/', TipoCanchaDeleteView.as_view(), name='tipo-eliminar'),

    # Agenda URLs
    path('agenda/listar/', AgendaListView.as_view(), name='agenda-listar'),
    path('agenda/agregar/', AgendaCreateView.as_view(), name='agenda-agregar'),
    path('agenda/actualizar/<int:pk>/', AgendaUpdateView.as_view(), name='agenda-actualizar'),
    path('agenda/eliminar/<int:pk>/', AgendaDeleteView.as_view(), name='agenda-eliminar'),

    # PreReserva URL
    path('agenda/reserva/', PreReserva.as_view(), name='agenda-reserva'),
]

servicio/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_migrate
from django.dispatch import receiver
from datetime import time



class TipoCancha(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=8, decimal_places=0)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Tipo de Cancha')
        verbose_name_plural = _('Tipos de Canchas')

class Cancha(models.Model):
    NUMERACION_CHOICES = [
        ('1', 'Cancha 1'),
        ('2', 'Cancha 2'),
        ('3', 'Cancha 3'),
        ('4', 'Cancha 4'),
        ('5', 'Cancha 5'),
        ('6', 'Cancha 6'),
        ('7', 'Cancha 7'),
        ('8', 'Cancha 8'),
    ]
    numeracion = models.CharField(max_length=10, choices=NUMERACION_CHOICES)
    tipo = models.ForeignKey(TipoCancha, on_delete=models.CASCADE, related_name='canchas')

    def __str__(self):
        return f'Cancha {self.numeracion}'

    class Meta:
        verbose_name = _('Cancha')
        verbose_name_plural = _('Canchas')

class Horario(models.Model):
    AM = 'AM'
    PM = 'PM'
    MERIDIEM_CHOICES = [
        (AM, 'AM'),
        (PM, 'PM'),
    ]
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    meridiem = models.CharField(max_length=2, choices=MERIDIEM_CHOICES, default=PM)

    #ESTA FUNCION GENERA LOS HORARIOS AUTOMATICAMENTE POR DEFECTO RELLENA LA CLASE HORARIO
    @classmethod
    def generar_horarios_default(cls):
        horarios_default_am = [
            (time(9, 0), time(10, 0)),
            (time(10, 0), time(11, 0)),
            (time(11, 0), time(12, 0)),
        ]

        horarios_default_pm = [
            (time(12, 0), time(13, 0)),
            (time(16, 0), time(17, 0)),
            (time(17, 0), time(18, 0)),
            (time(18, 0), time(19, 0)),
            (time(19, 0), time(20, 0)),
            (time(20, 0), time(21, 0)),
            (time(21, 0), time(22, 0)),
        ]

        for inicio, fin in horarios_default_am:
            horario, created = cls.objects.get_or_create(
                hora_inicio=inicio,
                hora_fin=fin,
                meridiem=cls.AM
            )
            if created:
                print(f'Se creó el horario AM: {horario}')

        for inicio, fin in horarios_default_pm:
            horario, created = cls.objects.get_or_create(
                hora_inicio=inicio,
                hora_fin=fin,
                meridiem=cls.PM
            )
            if created:
                print(f'Se creó el horario PM: {horario}')
    
    def __str__(self):
        return f'{self.hora_inicio.strftime("%I:%M %p")} - {self.hora_fin.strftime("%I:%M %p")}'

class Agenda(models.Model):
    cancha = models.ForeignKey(Cancha, on_delete=models.CASCADE)
    horario = models.ForeignKey(Horario, on_delete=models.CASCADE)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.cancha.tipo} {self.cancha} - {self.horario}'

    class Meta:
        verbose_name = _('Agenda')
        verbose_name_plural = _('Agendas')
        unique_together = ('cancha', 'horario')

#SE LAMA LA FUNCION GENERAR HORARIOS
@receiver(post_migrate)
def generar_horarios_default(sender, **kwargs):
    if sender.name == 'cliente': 
        Horario.generar_horarios_default()

servicio/forms.py
from django import forms
from .models import Cancha

class CanchaForm(forms.ModelForm):
    class Meta:
        model = Cancha
        fields = ['numeracion', 'tipo', 'precio']

servicio/views.py
from django.views.generic import ListView,CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Cancha,TipoCancha,Agenda
from cliente.models import Reserva
from django.utils import timezone
from cliente.models import Cliente

from django.contrib import messages
from django.shortcuts import redirect
from django.utils import timezone

from django.db.models import Q
from django.views.generic import ListView
from accounts.decorators import has_permission
from django.utils.decorators import method_decorator


from django.contrib.auth.decorators import login_required


class CanchaListView(ListView):
    model = Cancha
    template_name = 'servicios/listar.html'
    context_object_name = 'canchas'

class CanchaCreateView(CreateView):
    model = Cancha
    template_name = 'servicios/agregar.html'
    fields = '__all__'
    # form_class = ServicioForm

class CanchaUpdateView(UpdateView):
    model = Cancha
    template_name = 'servicios/actualizar.html'
    fields = '__all__'
    context_object_name = 'servicio'

class CanchaDeleteView(DeleteView):
    model = Cancha
    success_url = reverse_lazy('servicio-listar')

############# tipo ##############################
class TipoCanchaListView(ListView):
    model = TipoCancha
    template_name = 'servicios/tipo/listar.html'
    context_object_name = 'TipoCancha'

class TipoCanchaCreateView(CreateView):
    model = TipoCancha
    template_name = 'servicios/tipo/agregar.html'
    fields = '__all__'
    # form_class = ServicioForm

class TipoCanchaUpdateView(UpdateView):
    model = TipoCancha
    template_name = 'servicios/tipo/actualizar.html'
    fields = '__all__'
    context_object_name = 'TipoCancha'

class TipoCanchaDeleteView(DeleteView):
    model = TipoCancha
    success_url = reverse_lazy('TipoCancha-listar')


############# agenda ############################

from django.urls import reverse

class AgendaListView(ListView):
    model = Agenda
    template_name = 'agendas/listar.html'
    context_object_name = 'agendas'

    #ESTA FUNCION RECUERDA AL USUARIO ADMIN O TRABAJADOR RELLENAR SUS DATOS
    def dispatch(self, request, *args, **kwargs):
        user = self.request.user

        if not (user.name and user.apellidos):
            messages.warning(self.request, "Completa tu nombre y apellidos antes de continuar.")
            profile_url = reverse('account:update_user') 
            return redirect(profile_url)

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset = super().get_queryset()

        if query:
            queryset = queryset.filter(
                Q(cancha__tipo__nombre__icontains=query) |
                Q(cancha__numeracion__icontains=query) 
            )

        return queryset


class AgendaCreateView(CreateView):
    model = Agenda
    template_name = 'agendas/agregar.html'
    fields = '__all__'

class AgendaUpdateView(UpdateView):
    model = Agenda
    template_name = 'agendas/actualizar.html'
    fields = '__all__'
    context_object_name = 'agenda'

class AgendaDeleteView(DeleteView):
    model = Agenda
    success_url = reverse_lazy('agenda-listar')


#AQUI SE REALIZA EL PRIMER FILTRO YA QUE  NECESITAMOS QUE MUESTRE LOS TIPOS DE CANCHAS, LUEGO SEGUN EL TIPO.. LAS CANCHAS ASOCIADAS A ESE TIPO, LUEGO SEGUN LA CANCHAS MOSTRAR LAS AGENDAS(HORARIOS) ASOCIADAS AL TIPO DE CANCHA Y CANCHA ESCOGIDO ANTERIORMENTE.
class PreReserva(ListView):
    model = TipoCancha
    template_name = 'pre_reserva/pre_reserva.html'
    context_object_name = 'tipos_cancha'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('Login:login')

        try:
            cliente = request.user.cliente
        except Cliente.DoesNotExist:
            messages.warning(request, 'Necesitas los DATOS COMPLEMENTARIOS para realizar una reserva')
            return redirect('cliente:cliente_create')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        agendas_por_cancha = {}

        current_date = timezone.now().date()

        for tipo in context['tipos_cancha']:
            canchas = Cancha.objects.filter(tipo=tipo)
            agendas_por_cancha[tipo] = {}

            for cancha in canchas:
                agendas = Agenda.objects.filter(cancha=cancha, disponible=True)
                agendas_por_cancha[tipo][cancha] = agendas

        context['agendas_por_cancha'] = agendas_por_cancha

        return context

servicio/templates/pre_reserva/pre_reserva.html
{% extends "layout.html" %}

{% block title %}
Agendas | {{ block.super }}
{% endblock %}

{% load static %}
{% load humanize %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/servicio/agendas.css' %}" type="text/css">
{% endblock %}

{% block container %}

<!-- Tipos de Canchas -->
<div class="tipos-cancha">
  <div class="card-tipos">
    {% for tipo in tipos_cancha %}
      <div class="card">
        <a href="{% url 'servicio:agenda-reserva'%}">
          {% if tipo.nombre == "Futbolito" %}
            <img src="https://dummyimage.com/600x400/000/fff" alt="Imagen de la cancha de futbolito">
          {% elif tipo.nombre == "Paddel" %}
            <img src="https://dummyimage.com/600x400/000/fff" alt="Imagen de la cancha de paddel">
          {% elif tipo.nombre == "Cross" %}
            <img src="https://dummyimage.com/600x400/000/fff" alt="Imagen de la cancha de paddel">
          {% else %}
            <img src="https://dummyimage.com/600x400/000/fff" alt="Imagen predeterminada">
          {% endif %}
        </a>
        <div class="card-body">
          <h1>{{ tipo.nombre }} (<span>${{ tipo.precio|intcomma }}</span>)</h1>

          <p>{{ tipo.descripcion }}</p>
          <a href="#" class="card-link btn btn-outline-dark" data-toggle="modal" data-target="#canchasModal{{ tipo.id }}">Ver Canchas</a>
        </div>
      </div>
    {% endfor %}
  </div>
</div>


<!-- Modal para mostrar las canchas correspondientes a un tipo -->
{% for tipo in tipos_cancha %}
  <div class="modal" id="canchasModal{{ tipo.id }}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Canchas - {{ tipo.nombre }}</h5>
          <div data-dismiss="modal" aria-label="Close">
            <span id="close-modal" aria-hidden="true">&times;</span>
          </div>
        </div>
        <div class="modal-body">
          <div class="card-deck">
            {% for cancha in tipo.canchas.all %}
              <div class="card-canchas">
                <div class="card-body">
                  <h5 class="card-title">Cancha N°{{ cancha.numeracion }}</h5>
                  <a href="#" class="card-link btn btn-outline-dark" data-toggle="modal" data-target="#horariosModal{{ cancha.id }}">Ver Horarios</a>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

<!-- Submodal para mostrar los horarios de una cancha -->
{% for tipo, canchas_agendas in agendas_por_cancha.items %}
  {% for cancha, agendas in canchas_agendas.items %}
    <div class="modal" id="horariosModal{{ cancha.id }}">
      <div class="modal-dialog-agenda">
        <div id="modal-content-horarios"   class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Horarios - {{ cancha }}</h5>
            <div data-dismiss="modal" aria-label="Close">
              <span id="close-modal" aria-hidden="true">&times;</span>
            </div>
          </div>
          <div class="modal-body">
            <ul>
              {% for agenda in agendas %}
                <li><a href="{% url 'cliente:crear_reserva' agenda_id=agenda.id %}" >{{ agenda.cancha.tipo}} / {{ agenda.horario }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endfor %}

{% endblock %}